### ISSUE TITLE
query parser broken somewhere.

### ISSUE THREAD

**Issue by ellzey** [ellzey/libevhtp#158]
I've suddenly run into

```
mthomas@babby:~/Code/libevhtp/build$ ./test_query
- base_tests
  OK     a=b;key&c=val                            {"a": "b;key", "c": "val"}
  OK     a=b;key=val                              {"a": "b;key=val"}
  OK     a;b=val                                  {"a;b": "val"}
  OK     end_empty_string=               (error)  <error>
  OK     end_null                        (error)  <error>
  OK     hexa=some%20&hexb=bla%0                  {"hexa": "some%20", "hexb": "bla%0"}
  OK     hexa=some%20;hexb=bla                    {"hexa": "some%20;hexb=bla"}
  ERROR  hexa%z=some                              {"hexa%z": "some"}
```

Odd.

**Comment by ellzey** [comment]
@tjeezy can you look at this, my head hurts.

**Comment by tjeezy** [comment]
Taking a look.

**Comment by tjeezy** [comment]
On first impression... the test looks wrong, no? The key has an extra "%"?

**Comment by tjeezy** [comment]
Did `evhtp_kvs_find_kv` start / stop using format string somewhere? Still digging...

**Comment by ellzey** [comment]
It doesn't look like `evhtp_kvs_find_kv` would be the issue. I'm looking too. Not much has changed around that area in a while.

**Comment by ellzey** [comment]
Just noticed it's broken in master too.

**Comment by tjeezy** [comment]
Yep, noticed that too. But it doesn't look like the actual behavior of the parsing is bad... looks more like something is going wrong at test compare time.

**Comment by ellzey** [comment]
Seems to have been broken somewhere around e282b6fb9a7af0b00003af2b9931707a304b331d

**Comment by tjeezy** [comment]
Ah so it never worked? Woops! I think just removing the funky "\%" should fix it...

Could we add tests somewhere into the build / contrib process?

**Comment by ellzey** [comment]
https://github.com/ellzey/libevhtp/commit/61c7f4f33a799dea62b37d5f5abdc844cd1a6ea6?diff=unified#diff-4f8f037036c6ec8208f7a84e64aef4f8R2415

seems to be working here I think

**Comment by ellzey** [comment]
oops, here a6edc19c4fcff121ae99447355a6dd1808f1b265

**Comment by tjeezy** [comment]
https://github.com/ellzey/libevhtp/commit/a6edc19c4fcff121ae99447355a6dd1808f1b265#diff-4f8f037036c6ec8208f7a84e64aef4f8L2509

^ That?

**Comment by tjeezy** [comment]
Doesn't the issue have to do with the double "%%" for format string but single "%" for actual string compare?

**Comment by ellzey** [comment]
we have a wonky edge case.

**Comment by ellzey** [comment]
```C
                    case '%':
                        key_buf[key_idx++] = ch;
                        key_buf[key_idx]   = '\0';

                        if (!(flags & EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX)) {
                            state = s_query_key_hex_1;
                        }
```

Will go to 

```C
            case s_query_key_hex_1:
                if (!evhtp_is_hex_query_char(ch)) {
                    /* not hex, so we treat as a normal key */
                    if ((key_idx + 2) >= len) {
                        /* we need to insert \%<ch>, but not enough space */
                        goto error;
                    }

                    key_buf[key_idx - 1] = '%';
                    key_buf[key_idx++]   = ch;
                    key_buf[key_idx]     = '\0';

                    state = s_query_key;
                    break;
                }

                key_buf[key_idx++] = ch;
                key_buf[key_idx]   = '\0';

                state = s_query_key_hex_2;
```

Should we put a flag check in the `s_query_key_hex_1` state?

**Comment by tjeezy** [comment]
Oh, woops -- I was totally off track, but I get it now. Let's see...

**Comment by ellzey** [comment]
I think it's just the test

```
(gdb) print key_buf
$18 = 0x7fffffffe2c0 "hexa%z"
(gdb) print val_buf
$19 = 0x7fffffffe2b0 "some"
(gdb) s
evhtp_kv_new (key=0x7fffffffe2c0 "hexa%z", val=0x7fffffffe2b0 "some", kalloc=1 '\001', valloc=1 '\001') at /home/mthomas/Code/libevhtp/evhtp.c:2426
2426	    kv           = malloc(sizeof(evhtp_kv_t));
(gdb) n
2427	    evhtp_alloc_assert(kv);
(gdb) n
2429	    kv->k_heaped = kalloc;
(gdb)
2430	    kv->v_heaped = valloc;
(gdb)
2431	    kv->klen     = 0;
(gdb)
2432	    kv->vlen     = 0;
(gdb)
2433	    kv->key      = NULL;
(gdb)
2434	    kv->val      = NULL;
(gdb)
2436	    if (key != NULL) {
(gdb)
2437	        kv->klen = strlen(key);
(gdb)
2439	        if (kalloc == 1) {
(gdb)
2442	            if (!(s = malloc(kv->klen + 1))) {
(gdb)
2448	            memcpy(s, key, kv->klen);
(gdb)
2450	            s[kv->klen] = '\0';
(gdb) n
2451	            kv->key     = s;
(gdb)
2457	    if (val != NULL) {
(gdb)
2458	        kv->vlen = strlen(val);
(gdb)
2460	        if (valloc == 1) {
(gdb)
2461	            char * s = malloc(kv->vlen + 1);
(gdb)
2463	            s[kv->vlen] = '\0';
(gdb)
2464	            memcpy(s, val, kv->vlen);
(gdb)
2465	            kv->val     = s;
(gdb) print s
$20 = 0x6794f0 "some"
(gdb) n
2471	    return kv;
(gdb) print s
No symbol "s" in current context.
(gdb) print *kv
$21 = {
  key = 0x6794d0 "hexa%z",
  val = 0x6794f0 "some",
  klen = 6,
  vlen = 4,
  k_heaped = 1 '\001',
  v_heaped = 1 '\001',
  next = {
    tqe_next = 0x0,
    tqe_prev = 0x0
  }
}
(gdb) n
2472	}     /* evhtp_kv_new */
(gdb) n
evhtp_parse_query_wflags (query=0x436974 "hexa%z=some", len=11, flags=0) at /home/mthomas/Code/libevhtp/evhtp.c:2928
2928	                break;
(gdb)
2953	    return query_args;
(gdb) print *query_args
$22 = {
  tqh_first = 0x679490,
  tqh_last = 0x6794b8
}
(gdb) n
2961	}     /* evhtp_parse_query */
(gdb)
query_test (raw_query=0x436974 "hexa%z=some", exp_error=0, exp=0x6767e0 <base_tests+1248>, flags=0) at /home/mthomas/Code/libevhtp/examples/test_query.c:74
74	    if (!query) {
(gdb) print query
$23 = (evhtp_kvs_t *) 0x679470
(gdb) n
79	    printf("{");
(gdb)
80	    evhtp_kvs_for_each(query, kvs_print, &key_idx);
(gdb) print key_idx
$24 = 0
(gdb) s
evhtp_kvs_for_each (kvs=0x679470, cb=0x403abf <kvs_print>, arg=0x7fffffffe3c4) at /home/mthomas/Code/libevhtp/evhtp.c:2526
2526	    if (kvs == NULL || cb == NULL) {
(gdb) n
2530	    TAILQ_FOREACH(kv, kvs, next) {
(gdb)
2533	        if ((res = cb(kv, arg))) {
(gdb) print *kv
$25 = {
  key = 0x6794d0 "hexa%z",
  val = 0x6794f0 "some",
  klen = 6,
  vlen = 4,
  k_heaped = 1 '\001',
  v_heaped = 1 '\001',
  next = {
    tqe_next = 0x0,
    tqe_prev = 0x679470
  }
}
(gdb) n
2530	    TAILQ_FOREACH(kv, kvs, next) {
(gdb)
2538	    return 0;
(gdb)
2539	}
(gdb)
query_test (raw_query=0x436974 "hexa%z=some", exp_error=0, exp=0x6767e0 <base_tests+1248>, flags=0) at /home/mthomas/Code/libevhtp/examples/test_query.c:82
82	    printf("}");
(gdb) n
85	        evhtp_kv_t * kvobj  = NULL;
(gdb) n
86	        const char * valstr = NULL;
(gdb)
88	        check = &exp[idx++];
(gdb) print check
$26 = (struct expected *) 0x676740 <base_tests+1088>
(gdb) n
90	        if (check == NULL || check->key == NULL) {
(gdb)
94	        kvobj  = evhtp_kvs_find_kv(query, check->key);
(gdb) print query
$27 = (evhtp_kvs_t *) 0x679470
(gdb) print * query
$28 = {
  tqh_first = 0x679490,
  tqh_last = 0x6794b8
}
(gdb) print check->key
$29 = 0x436980 "hexa%%z"
````

**Comment by ellzey** [comment]
````diff
diff --git a/examples/test_query.c b/examples/test_query.c
index fe4adc2..7f1be19 100644
--- a/examples/test_query.c
+++ b/examples/test_query.c
@@ -133,7 +133,7 @@ struct test base_tests[] = {
                 { NULL,                      NULL },
             } },
     { "hexa%z=some",             0, {
-                { "hexa\%%z",                "some" },
+                { "hexa%z",                "some" },
                 { NULL,                      NULL },
             } },
     { "aaa=some\%az",            1 },
```

Passes.

**Comment by tjeezy** [comment]
You are doing a really good job of confusing me! :confused: :smile: 

Like I said in the beginning, `evhtp_kvs_find_kv` is looking for a key with double "%"... (which you are showing in `check->key` while the actual key is "hexa%z"), right? The tests print correctly because of format string but the actual string used in compare is wrong.

I don't understand why we would add a flag check in `s_query_key_hex_1`.

**Comment by tjeezy** [comment]
Hmmm... deja-vu?

https://github.com/ellzey/libevhtp/issues/158#issuecomment-84089919 :stuck_out_tongue: 

PS: Sorry for adding this broken!! :disappointed:

**Comment by ellzey** [comment]
Trust me, I am as confused as you; what are the _expectations_, should `"hexa\%%z"` really get converted to `"hexa%z"`?

**Comment by ellzey** [comment]
>> PS: Sorry for adding this broken!!

no problem, I was just wondering if __I__ did something wrong.

**Comment by ellzey** [comment]
Fixed 2d4c22f14a2e689999579483724a97860ec7e4ca

Thanks for helping me out!

**Comment by tjeezy** [comment]
Wait, wait! I think we might still have a problem. We should clarify the expectations like you said.

When we have `_IGNORE_HEX` flag, I think we *do* need to insert the backslash? Maybe the test should instead be checking for "\\%" instead of "\%%"?

**Comment by ellzey** [comment]
this function is making me die a little inside.

**Comment by tjeezy** [comment]
Does libevent 2's HTTP module still just do it super wrong like libevent 1.4's?

**Comment by tjeezy** [comment]
Hmm... looks *too* simple (they still crap-out if they don't find `=`?!):

https://github.com/libevent/libevent/blob/master/http.c#L3053

**Comment by ellzey** [comment]
lol, why do you even look at that? I stay far away from it.

**Comment by tjeezy** [comment]
Haha. So how do we make you die a little less inside while having a decent query parser?

I don't think it's too bad... but the urlencoding is a bit of a pain (especially with the string escaping).

**Comment by ellzey** [comment]
We can figure that out in the future. This works now.
