### ISSUE TITLE
libevhtp https server crash when client press the Ctrl-C

### ISSUE THREAD

**Issue by dorlan** [ellzey/libevhtp#195]
thanks friend.  I am chinese developer. 
In trying to write a simple test of the process found the problem。
server:
![qq 20151117150458](https://cloud.githubusercontent.com/assets/15884535/11204782/2cef7e7c-8d3d-11e5-8345-02ebd94a5a78.png)
![qq 20151117150444](https://cloud.githubusercontent.com/assets/15884535/11204803/5a52a600-8d3d-11e5-8171-a49ed3d26d67.png)

client:
![qq 20151117150550](https://cloud.githubusercontent.com/assets/15884535/11204824/7ad0c8b2-8d3d-11e5-83a6-d8eaa18b6c0d.png)

The reason for this exception, mainly in the client after the request to send a request, the random interruption, a great probability of causing the server crash.
Server function is very simple, is to query the database, and then the data has been returned to the JSON format to the client.
![qq 20151117151510](https://cloud.githubusercontent.com/assets/15884535/11204890/06143224-8d3e-11e5-8400-236e6160d3b6.png)

When the script is running, the Ctrl-C interrupt script is executed, and it will lead to the collapse of the service.
![qq 20151117151634](https://cloud.githubusercontent.com/assets/15884535/11204906/396dd102-8d3e-11e5-9567-e5d13d09cdf3.png)

And I also tried the test.c code in the example, make a little change and test.
![qq 20151117145920](https://cloud.githubusercontent.com/assets/15884535/11204949/a3c3b2a6-8d3e-11e5-8016-2625ca9eb5d0.png)

Crash too.
![qq 20151117145844](https://cloud.githubusercontent.com/assets/15884535/11204961/c55450d8-8d3e-11e5-94df-df7cfca80b25.png)
![qq 20151117145900](https://cloud.githubusercontent.com/assets/15884535/11204972/e0a1328e-8d3e-11e5-898e-c70197dd8e96.png)

and the test client script is:
![qq 20151117150032](https://cloud.githubusercontent.com/assets/15884535/11204986/fa759baa-8d3e-11e5-8f98-2ef5ce76b86a.png)

The problem occurs when I press Ctrl-C。
Thanks any one to help me.

**Comment by dorlan** [comment]
The problem is only in HTTPS.
I modified the test_basic.c to make it support SSL。
![qq 20151120143122](https://cloud.githubusercontent.com/assets/15884535/11293293/d565795a-8f93-11e5-8ca3-4baa8091a21a.png)
![qq 20151120143149](https://cloud.githubusercontent.com/assets/15884535/11293334/3ae350e0-8f94-11e5-9369-222b8bb7e8cc.png)

Segmentation fault (core dumped)
![qq 20151120143313](https://cloud.githubusercontent.com/assets/15884535/11293351/57d8bf50-8f94-11e5-9e12-210cfe3829f9.png)

I use the following way to test：
wget -4 https://localhost:8084/simple/ --no-check-certificate

**Comment by adamel** [comment]
What version are you testing with?

**Comment by dorlan** [comment]
1.2.10 and  1.2.11 both this program.
My Host is: CentOS release 6.7 (Final)

**Comment by ellzey** [comment]
What version of libevent?

**Comment by dorlan** [comment]
libevent 2.0.22

**Comment by ellzey** [comment]
The fact the eventcb is executed then readcb is called seems odd.

**Comment by ellzey** [comment]
I see hints of libnss symbols in your bt, are you linked against openssl or libnss?

**Comment by adamel** [comment]
Umm, just realized those are screenshots! :-( Never post screenshots of text. Please provide your updated test_basic.c in a useful format.

**Comment by dorlan** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <evhtp.h>

void
testcb(evhtp_request_t * req, void * a) {
    const char * str = a;

	sleep(2);
    evbuffer_add(req->buffer_out, str, strlen(str));
    evhtp_send_reply(req, EVHTP_RES_OK);
}

void
issue161cb(evhtp_request_t * req, void * a) {
    struct evbuffer * b = evbuffer_new();

    if (evhtp_request_get_proto(req) == EVHTP_PROTO_10) {
        evhtp_request_set_keepalive(req, 0);
    }

    evhtp_send_reply_start(req, EVHTP_RES_OK);

    evbuffer_add(b, "foo", 3);
    evhtp_send_reply_body(req, b);

    evbuffer_add(b, "bar\n\n", 5);
    evhtp_send_reply_body(req, b);

    evhtp_send_reply_end(req);

    evbuffer_free(b);
}

int
main(int argc, char ** argv) {
    evbase_t * evbase = event_base_new();
    evhtp_t  * htp    = evhtp_new(evbase, NULL);

    evhtp_set_cb(htp, "/simple/", testcb, "simple");
    evhtp_set_cb(htp, "/1/ping", testcb, "one");
    evhtp_set_cb(htp, "/1/ping.json", testcb, "two");
    evhtp_set_cb(htp, "/issue161", issue161cb, NULL);
#ifndef EVHTP_DISABLE_EVTHR
    evhtp_use_threads(htp, NULL, 8, NULL);
#endif

	char ciphers[256] = "RC4+MD5:RC4-SHA:DES-CBC3-SHA:RC4+RSA:HIGH:+MEDIUM:+LOW";
	/* ssl support */
	evhtp_ssl_cfg_t scfg = {0};
	scfg.pemfile            = "/etc/wpdconfig/server.crt";
	scfg.privfile           = "/etc/wpdconfig/server.key";
	scfg.cafile             = "/etc/wpdconfig/ca.crt";
	scfg.capath             = "/etc/wpdconfig/";
	scfg.ciphers            = ciphers;
	scfg.ssl_opts           = SSL_OP_NO_SSLv2;
	scfg.ssl_ctx_timeout    = 60 * 60 * 48;
	scfg.verify_peer        = SSL_VERIFY_NONE;
	scfg.verify_depth       = 42;
	scfg.x509_verify_cb     = NULL;
	scfg.x509_chk_issued_cb = NULL;
	scfg.scache_type        = evhtp_ssl_scache_type_internal;
	scfg.scache_size        = 1024;
	scfg.scache_timeout     = 1024;
	scfg.scache_init        = NULL;
	scfg.scache_add         = NULL;
	scfg.scache_get         = NULL;
	scfg.scache_del         = NULL;

	if (evhtp_ssl_init(htp,&scfg) == -1)
	{
		printf("evhtp_ssl_init failed\n");
		return 0;
	}
    evhtp_bind_socket(htp, "0.0.0.0", 8084, 2048);

    event_base_loop(evbase, 0);

    evhtp_unbind_socket(htp);
    evhtp_free(htp);
    event_base_free(evbase);

    return 0;
}

**Comment by dorlan** [comment]
@ellzey   the first application, used these libraries.
 -levhtp -levent -lpthread -lssl -lrt -lxml2 -lmysqlclient

**Comment by ellzey** [comment]
I'm watching the arrow and can't stop, in the mean time can you post a valgrind if you are able?

**Comment by dorlan** [comment]
@ellzey valgrind's output is very long, Are all pasted here??

**Comment by ellzey** [comment]
gist it

**Comment by dorlan** [comment]
==24597== 16,560 bytes in 1 blocks are still reachable in loss record 395 of 396
==24597==    at 0x4007159: malloc (vg_replace_malloc.c:270)
==24597==    by 0x41FFE2E: ??? (in /usr/lib/libcrypto.so.1.0.1e)
==24597==    by 0x4200398: CRYPTO_malloc (in /usr/lib/libcrypto.so.1.0.1e)
==24597==    by 0x46E27A4: ??? (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E28AE: ssl3_setup_write_buffer (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E2A52: ssl3_setup_buffers (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E523E: ssl23_get_client_hello (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E57E4: ssl23_accept (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46F914D: SSL_do_handshake (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x40639F5: do_handshake (bufferevent_openssl.c:1003)
==24597==    by 0x4063D38: be_openssl_handshakeeventcb (bufferevent_openssl.c:1056)
==24597==    by 0x4052823: event_base_loop (event.c:1319)
==24597== 
==24597== 16,712 bytes in 1 blocks are still reachable in loss record 396 of 396
==24597==    at 0x4007159: malloc (vg_replace_malloc.c:270)
==24597==    by 0x41FFE2E: ??? (in /usr/lib/libcrypto.so.1.0.1e)
==24597==    by 0x4200398: CRYPTO_malloc (in /usr/lib/libcrypto.so.1.0.1e)
==24597==    by 0x46E27A4: ??? (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E29BA: ssl3_setup_read_buffer (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E2A42: ssl3_setup_buffers (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E523E: ssl23_get_client_hello (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46E57E4: ssl23_accept (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x46F914D: SSL_do_handshake (in /usr/lib/libssl.so.1.0.1e)
==24597==    by 0x40639F5: do_handshake (bufferevent_openssl.c:1003)
==24597==    by 0x4063D38: be_openssl_handshakeeventcb (bufferevent_openssl.c:1056)
==24597==    by 0x4052823: event_base_loop (event.c:1319)
==24597== 
==24597== LEAK SUMMARY:
==24597==    definitely lost: 0 bytes in 0 blocks
==24597==    indirectly lost: 0 bytes in 0 blocks
==24597==      possibly lost: 0 bytes in 0 blocks
==24597==    still reachable: 96,730 bytes in 3,214 blocks
==24597==         suppressed: 0 bytes in 0 blocks
==24597== 
==24597== For counts of detected and suppressed errors, rerun with: -v
==24597== ERROR SUMMARY: 12 errors from 12 contexts (suppressed: 28 from 8)
Segmentation fault (core dumped)

**Comment by ellzey** [comment]
thanks

**Comment by dorlan** [comment]
@ellzey 
==24597== Invalid read of size 4
==24597==    at 0x4055BC9: evbuffer_add_buffer (buffer.c:908)
==24597==    by 0x405997D: bufferevent_write_buffer (bufferevent.c:388)
==24597==    by 0x40219B4: evhtp_send_reply (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x8048A64: testcb (in /usr/local/cgswh/libevhtp-develop/examples/test_basic)
==24597==    by 0x401EF06: _evhtp_request_parser_fini (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x4024937: hook_on_msg_complete_run (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x402734D: htparser_run (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x401F562: _evhtp_connection_readcb (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x405A0B6: _bufferevent_run_readcb (bufferevent.c:232)
==24597==    by 0x4065225: consider_reading (bufferevent_openssl.c:825)
==24597==    by 0x4065257: be_openssl_readeventcb (bufferevent_openssl.c:938)
==24597==    by 0x4052823: event_base_loop (event.c:1319)
==24597==  Address 0x479ae50 is 24 bytes inside a block of size 76 free'd
==24597==    at 0x4006B66: free (vg_replace_malloc.c:446)
==24597==    by 0x4023A41: evhtp_connection_free (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x401F9F8: _evhtp_connection_eventcb (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x4059F3D: _bufferevent_run_eventcb (bufferevent.c:267)
==24597==    by 0x40638F2: conn_closed (bufferevent_openssl.c:531)
==24597==    by 0x4064E81: do_write (bufferevent_openssl.c:694)
==24597==    by 0x4064FC2: consider_writing (bufferevent_openssl.c:874)
==24597==    by 0x4054C66: evbuffer_run_callbacks (buffer.c:494)
==24597==    by 0x4055D10: evbuffer_add_buffer (buffer.c:905)
==24597==    by 0x405997D: bufferevent_write_buffer (bufferevent.c:388)
==24597==    by 0x40219B4: evhtp_send_reply (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x8048A64: testcb (in /usr/local/cgswh/libevhtp-develop/examples/test_basic)
==24597== 
==24597== Invalid read of size 4
==24597==    at 0x4057E92: evbuffer_drain (buffer.c:965)
==24597==    by 0x40219C7: evhtp_send_reply (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x8048A64: testcb (in /usr/local/cgswh/libevhtp-develop/examples/test_basic)
==24597==    by 0x401EF06: _evhtp_request_parser_fini (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x4024937: hook_on_msg_complete_run (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x402734D: htparser_run (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x401F562: _evhtp_connection_readcb (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x405A0B6: _bufferevent_run_readcb (bufferevent.c:232)
==24597==    by 0x4065225: consider_reading (bufferevent_openssl.c:825)
==24597==    by 0x4065257: be_openssl_readeventcb (bufferevent_openssl.c:938)
==24597==    by 0x4052823: event_base_loop (event.c:1319)
==24597==    by 0x8048DA0: main (in /usr/local/cgswh/libevhtp-develop/examples/test_basic)
==24597==  Address 0x479ae50 is 24 bytes inside a block of size 76 free'd
==24597==    at 0x4006B66: free (vg_replace_malloc.c:446)
==24597==    by 0x4023A41: evhtp_connection_free (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x401F9F8: _evhtp_connection_eventcb (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x4059F3D: _bufferevent_run_eventcb (bufferevent.c:267)
==24597==    by 0x40638F2: conn_closed (bufferevent_openssl.c:531)
==24597==    by 0x4064E81: do_write (bufferevent_openssl.c:694)
==24597==    by 0x4064FC2: consider_writing (bufferevent_openssl.c:874)
==24597==    by 0x4054C66: evbuffer_run_callbacks (buffer.c:494)
==24597==    by 0x4055D10: evbuffer_add_buffer (buffer.c:905)
==24597==    by 0x405997D: bufferevent_write_buffer (bufferevent.c:388)
==24597==    by 0x40219B4: evhtp_send_reply (in /usr/local/cgswh/libevhtp-develop/libevhtp.so.1.2.10)
==24597==    by 0x8048A64: testcb (in /usr/local/cgswh/libevhtp-develop/examples/test_basic)

**Comment by adamel** [comment]
Above pull request should fix the problem.

(Note the the livevent documentation lies - bufferevent_lock() certainly has effect regardless of whether thread support was compiled into libevent or not. In addition to the thread safety lock it also increases the reference counter of the bufferevent).

I wonder though if it wouldn't be nice if libevhtp had it's own reference counters on connections and requests?

**Comment by dorlan** [comment]
@adamel 
I used #197 evhtp.c code, but this error still exists.

**Comment by adamel** [comment]
You are right - the patch works for 1.2.10, but not for 1.2.11, due to the evbuffer returned from `_evhtp_create_reply()` being freed by `evhtp_connection_free()` in 1.2.11.

Please try the following patch on 1.2.11:
```
diff --git a/examples/test_basic.c b/examples/test_basic.c
index fcf107b..1ac1657 100644
--- a/examples/test_basic.c
+++ b/examples/test_basic.c
@@ -12,7 +12,9 @@ testcb(evhtp_request_t * req, void * a) {
 
     sleep(2);
     evbuffer_add(req->buffer_out, str, strlen(str));
+    evhtp_request_pause(req);
     evhtp_send_reply(req, EVHTP_RES_OK);
+    evhtp_request_resume(req);
 }
 
 void
```

with the above patch the changes to evhtp.c should actually not be needed.

It is however not very nice to force applications to surround each call to `evhtp_send_*()`
with pause/resume, so now I'm leaning even more to having evhtp connections and requests reference counted internally.

**Comment by ellzey** [comment]
a while back I started an overhaul mainly for these types of issues. there
was a bitmask for various states and a counter.

but in the current state, poor design on my part; adding such a thing turns
out to be a pain. Most of those odd edge cases were to deal with pipelined
requests.

I think the overhaul should be resurrected.

Screw backwards compatibility, we need better, cleaner design.

**Comment by dorlan** [comment]
@adamel  is ok,runing normal.

**Comment by ellzey** [comment]
> It is however not very nice to force applications to surround each call to evhtp_send_*()
with pause/resume

This wasn't the intended use. Technically it was a method of stopping the current request processing to allow for an application to do some dirty work, and resume processing afterwards. If this is the fix, then yes, that is bad.

**Comment by ellzey** [comment]
Also, maybe setting the deferred flag may be the answer. That would fix the case of immediate sends via bufferevent_add -> evbuffer_write -> send() -> error -> call errorcb and back again.

**Comment by ellzey** [comment]
Try the develop tree with #197 applied.

**Comment by pchero** [comment]
I just created pull request for this bug.

The problem was, if the ssl connection makes error during the reading the evbuffer, it fires event/error callback. Then the libevhtp free the connection handler.

And later, the libevhtp tries connection free again.

**Comment by ellzey** [comment]
Ref: https://github.com/ellzey/libevhtp/compare/feature/resume_fixes

This is a prototype of reworking the pause resume stuff.
